### ISSUE TITLE
Streamlit page resetting

### ISSUE THREAD

**Issue by m-wrzr** [m-wrzr/streamlit-searchbox#1]
This bug causes the page completely reload, resetting the state for all components.

Can be reproduced by quick typing compared to the function length _(at least sometimes)_. However, this is not caused the execution length of the lookup itself.

Possible Causes:
- Jump between states, e.g. `search: abc` -> `search: abcdefg` 
- Triggering `experimental_reload` as a form of soft refresh

**Comment by zronghui** [comment]
same，In my case, it always crashes, automatically refreshes the page, and doesn't work at all

**Comment by m-wrzr** [comment]
Can you provide more details regarding the crash/refresh and how to reliably reproduce it? I haven't run into this in a while, so any information would be appreciated.
