### ISSUE TITLE
Syntax error when calling the package

### ISSUE THREAD

**Issue by harithzulfaizal** [m-wrzr/streamlit-searchbox#10]
I seem to encounter this error when calling the package, SyntaxError: File "C:\Users\gpharith\Documents\gpt3-policydoc\openai_venv\lib\site-packages\streamlit_searchbox\__init__.py", line 108 match interaction: ^ SyntaxError: invalid syntax

**Comment by alikimav** [comment]
I think it's because the match case statement is introduced in python 3.10?

**Comment by m-wrzr** [comment]
Thanks for reporting the error. 

@alikimav you're right, I've removed the `match` to support older python versions, thank you for the input!
