### ISSUE TITLE
cannot inject typed text into search box as first value 

### ISSUE THREAD

**Issue by Maniwar** [m-wrzr/streamlit-searchbox#16]
anyway i can add whatever I'm typing into the select list? If it's not on the suggestions, i can't pick my own text. seems to work on localhost, but not on cloud.

**Comment by Maniwar** [comment]
seems to work on pc, but not on mobile.

**Comment by Maniwar** [comment]
<img width="1300" alt="Screenshot 2023-05-09 at 10 19 00 PM" src="https://github.com/m-wrzr/streamlit-searchbox/assets/14303810/1051db65-68c6-45fe-bb6e-2ab61a7db660">
local-host above
cloud below
![Screenshot 2023-05-09 at 10 19 34 PM](https://github.com/m-wrzr/streamlit-searchbox/assets/14303810/4483acd3-a0e0-4ca1-8549-2d63485c8423)

**Comment by Maniwar** [comment]
![Screenshot 2023-05-09 at 10 20 41 PM](https://github.com/m-wrzr/streamlit-searchbox/assets/14303810/ff9a09d4-3090-4a6d-950a-db3dbb7e7835)

**Comment by m-wrzr** [comment]
Hey, could it be an sorting issue? Both localhost/cloud seem to have different result lists?

Otherwise, if you want to make sure the input is available in the selections, it would have to be added to the provided search function.

**Comment by Maniwar** [comment]
Thank you! My mistake. This fixed it

# Insert the user input as the first option
results.insert(0, query)
