### ISSUE TITLE
How to change the value externally via `st.session_state`?

### ISSUE THREAD

**Issue by samsucik** [m-wrzr/streamlit-searchbox#17]
I'm struggling to make changes to the value displayed in the searchbox. Does anyone have any advice?

What I've tried so far:
- in my Streamlit app's code, changing `st.session_state.<searchbox_key>["result"]`
- making the same change but instead in the searchbox component's `__init__.py` (roughly [here](https://github.com/m-wrzr/streamlit-searchbox/blob/a5f27d6a36caa59cc3b7a0a6db722448a66aa4c1/streamlit_searchbox/__init__.py#L72))

While the entry in `st.session_state` changes, the searchbox continues do display just the default placeholder (`Search ...`).

Fyi I'm using the [0.1.3 version installed from PyPi](https://pypi.org/project/streamlit-searchbox/0.1.3/)

**Comment by m-wrzr** [comment]
Typically the values displayed are driven by the `search_function` that is passed to the component. If you want to run it without the search function you can also set the `options` manually, (the `search` state is handled via react), See the example below:

```
key = f"{search.__name__}_manual"
n_options = st.slider("slider", 0, 10, 5, key="slider")

if key in st.session_state:
    st.session_state[key]["options_js"] = [
        {"label": f"{st.session_state[key]['search']}_{i}", "value": i}
        for i in range(n_options)
    ]
    st.session_state[key]["options_py"] = [i for i in range(n_options)]

manual = st_searchbox(
    search_function=lambda _: [],
    key=key,
)


st.write(manual)
```
