### ISSUE TITLE
Set initial search or initial list of items

### ISSUE THREAD

**Issue by hoggatt** [m-wrzr/streamlit-searchbox#21]
Hi, there are cases where someone will just click on the box and I want to show all possible items. Right now, the search function isn't called until the user types something. Can there be an option to call the search function on click (or simply give it a list of items to show by default?).

**Comment by hoggatt** [comment]
It would also be nice if there was an option to disable 'st.experimental_rerun()'. This can mess things up sometimes depending on the app. Just returning the value might be good enough. Alternatively, have it only do a rerun when 'enter' is pressed.

**Comment by m-wrzr** [comment]
Thanks for the suggestions! I've added a `rerun_on_update` option to disable rerunning and a `default_options` list similar to the selection defaults, which can provide an option list before the first suggestion.

**Comment by hoggatt** [comment]
Thanks so much! One quick thing, I think you forgot the update the doc for the `st_searchbox` [here](https://github.com/m-wrzr/streamlit-searchbox/blob/287bebcc2415cb5b4d732b0829781c88481ee43c/streamlit_searchbox/__init__.py#L94C5-L94C20). 

There are two other functions I think could be helpful for people (although I don't personally need them so I won't make a new issue):
1. Allow specifying a reset_function (along with the search_function). Then when the box is cleared, something in the streamlit app can be run. This can be useful if you want to prevent certain things from happening if the searchbox is reset. 
2. Allow specifying a 'blank search value". When the box is blank (ie newly created or reset): run a search. This is similar to setting the default list (what you just implemented), but it would re-run the search each time it is cleared so it's up-do-date. Since streamlit re-runs a lot, this one might not be as helpful.
