### ISSUE TITLE
`st.experimental_rerun` will be removed after 2024-04-01. Alerting

### ISSUE THREAD

**Issue by twyangqian** [m-wrzr/streamlit-searchbox#27]
`st.experimental_rerun` will be removed after 2024-04-01.
2023-10-26 15:38:23.600 Please replace `st.experimental_rerun` with `st.rerun`.

**Comment by Jumitti** [comment]
i do a pull request to patch this. If you download and install manually the packages, it will works

**Comment by m-wrzr** [comment]
should be fixed in version `0.1.6` https://github.com/m-wrzr/streamlit-searchbox/pull/28 - please reopen it in case you're still encountering issues!
