### ISSUE TITLE
How to reset to my default_options after pressing reset button?

### ISSUE THREAD

**Issue by rex-lui** [m-wrzr/streamlit-searchbox#31]
Hi,

Nice to meet you and I am currently trying to use this package.
I faced an issue and hoped that anyone may solve me out.

I typed a search term to shorten my selection list and then I selected one of the value from it.
When I clicked the reset button and clicked the small triangle button again, the list showing to me was not the default list which I set, it's still the shorten list instead.
It would be good if the default list is always still showing up whenever the user click on reset button.

May I know anyway I can fix this?
Thanks a lot.

**Comment by m-wrzr** [comment]
Hey, sorry for the late response and thanks for the suggestion! I've added a general reset to the searchbox when the user clicks the clear button. Now the behavior should be as you described from versions >= `0.1.7`
