### ISSUE TITLE
Edit selected value for resubmission

### ISSUE THREAD

**Issue by gtzanet** [m-wrzr/streamlit-searchbox#35]
Hi, I am using the searchbox for some time, but I'm wondering if there is any way to keep editing the content after selection. I'm trying to make an autocomplete tool and other that that the widget is perfect for what I want. After I select a suggestion I want to be able to edit it (e.g. delete a word etc.) so that I get new suggestions without writing the prompt from scratch. Thanks in advance.

**Comment by m-wrzr** [comment]
Hey, sorry for the late response. I've added a new option `edit_after_submit` in the latest version. There are options to keep the current input editable `current`, use the suggested `option` or the `concat` both. 

Hope that helps with your usecase.

**Comment by m-wrzr** [comment]
example usage: https://github.com/m-wrzr/streamlit-searchbox/issues/38#issuecomment-2055280719
