### ISSUE TITLE
Pass additional parameters to the search function

### ISSUE THREAD

**Issue by denisvirissimo** [m-wrzr/streamlit-searchbox#38]
Is it possible to pass other parameters to the search function besides the searchterm?

If not, maybe considering this as an enhancement would be nice.

**Comment by m-wrzr** [comment]
Do you mean passing additional `kwargs` to `st_searchbox` and then forward them in the callback? The only data we get back from react is the current input and/or a selection?

**Comment by Willianjesusdasilva** [comment]
Hi m-wrzr, how are you?
When I think about a search box, Google search box is the first option that comes to mind.
I think, let's put my question here... and if this autocomplete doesn't work, I will add a new question.

Can i do it now? is to hard for implement it?

**Comment by denisvirissimo** [comment]
> Do you mean passing additional `kwargs` to `st_searchbox` and then forward them in the callback? The only data we get back from react is the current input and/or a selection?

Yeah, passing like kwargs that would be forwarded to the function that executes the search

**Comment by m-wrzr** [comment]
@denisvirissimo I've just released a new version `0.1.9` where the the `kwargs` are forwarded. Thanks for the suggestion!

**Comment by m-wrzr** [comment]
@Willianjesusdasilva 

can you try using `edit_after_submit="option"`? also check out this issue: https://github.com/m-wrzr/streamlit-searchbox/issues/35 - looks like this:



https://github.com/m-wrzr/streamlit-searchbox/assets/6058447/8ea768ed-bac2-43c1-8f91-d7c10e67fcd3
