### ISSUE TITLE
Feedback when the searchbox is selected

### ISSUE THREAD

**Issue by hansthen** [m-wrzr/streamlit-searchbox#4]
Is it possible to give some visual feedback when the searchbox is ready to accept search terms?

When the user wants to change an earlier entered search term, they click on the searchbox. However it is not immediately clear they can start a new search. A few suggestions on how to implement this, but I am sure many more are possible:

1. Add a background color to the search text (like in the browser location bar when it is selected).
2. Open the dropdown as soon as the searchbox is selected (like in the google search box).

**Comment by m-wrzr** [comment]
The searchbox now has a colored border when focused and ready to accept searchterms, in addition to the dropdown/clear icons this hopefully indicates the state a bit better.

Thanks for the feedback! Any additional input on visual improvements would be very appreciated!
