### ISSUE TITLE
_process_search function with incorrect parameter

### ISSUE THREAD

**Issue by henriquesousa7** [m-wrzr/streamlit-searchbox#40]
The `kwargs` parameter of the `_process_search` function seems incorrect to me, it is becoming mandatory in my application that uses this function.

wouldn't the correct one be `**kwargs`?

vide https://github.com/m-wrzr/streamlit-searchbox/blob/main/streamlit_searchbox/__init__.py#L76C5-L76C20

**Comment by m-wrzr** [comment]
Thanks for the input, I've updated the call to not pass `kwargs` explicitly. What is the usecase for calling `_process_search` directly?

**Comment by henriquesousa7** [comment]
I'm using it to view all searchbox items in the first interaction, removing the need to type any item to view
