### ISSUE TITLE
Can't see paste menu option

### ISSUE THREAD

**Issue by metalshanked** [m-wrzr/streamlit-searchbox#43]
Thanks for this awesome tool. 
I can't see the "paste" menu option in the browser on right click
Also, cant find a way to paste clipboard text into the search box on a mobile device.

Any advise thanks!

![image](https://github.com/m-wrzr/streamlit-searchbox/assets/57646596/5b35a92d-ffa3-4ef4-a2cc-20a4409573b1)

**Comment by m-wrzr** [comment]
Hey, thanks for the bug report. This issue should be fixed in the latest version `0.1.11`.

The reason was some non-mobile friendly default behavior in the underlying `react-select` library https://github.com/JedWatson/react-select/issues/4106
