### ISSUE TITLE
Change margin-bottom

### ISSUE THREAD

**Issue by vishhvak** [m-wrzr/streamlit-searchbox#52]
How can I change the margin-bottom or margins on the searchbox?

![image](https://github.com/user-attachments/assets/4c5e0efa-d6d4-45ed-85fe-d8614f085f02)

I'd like to make sure they are aligned with buttons

**Comment by m-wrzr** [comment]
hey, with the latest version `0.1.14` you can pass styles to position like this:

```
st_searchbox(
    search_function=search_wikipedia_ids,
    key="searchx",
    style_overrides=StyleOverrides(
        wrapper={"padding-top": "50px", "padding-left": "150px"},
    ),
)
```

otherwise, you can maybe place empty blocks `st.markdown("")` before/after?
