### ISSUE TITLE
Add `reset_function` callback option

### ISSUE THREAD

**Issue by hoggatt** [m-wrzr/streamlit-searchbox#58]
Add a callback function that can be run in the case of a reset. 

This is useful if you want to change some value in your app in the case of a reset. Pulling from my [fork](https://github.com/hoggatt/st-combobox/blob/master/st_combobox/__init__.py) that, unfortunately, I have so it won't let me make a pull request.

To the main function add this argument:
`reset_function: Callable[[], None] = None,`

With this doc string:
```
reset_function (Callable[[], None], optional):
    Function that is called after the user has reset the combobox. Defaults to None.
```

Then this needs to be in the `if interaction == "reset":` block, before the return:
```
if reset_function is not None:
    reset_function()
```

**Comment by hoggatt** [comment]
Here is the docstring in the readme:

---

```
reset_function: Callable[[], None] = None
```
Function that will be called when the combobox is reset.

**Comment by m-wrzr** [comment]
Thanks for the input! I'll add it to the next version 👍 https://github.com/m-wrzr/streamlit-searchbox/pull/59
