### ISSUE TITLE
searches only the listed items

### ISSUE THREAD

**Issue by Hariharan2019** [m-wrzr/streamlit-searchbox#6]
The search button or the magnifying icon does nothing. When you enter a search team which is not in the list and hit enter it doesn't seem to work. Also once you select one item from the list, the search bar does not remove it or clean it.

**Comment by m-wrzr** [comment]
Hey, the magnifying icon is removed in the current version. Thanks for the feedback, it was indeed just an empty icon and is now replaced with a dropdown and clear.
