### ISSUE TITLE
Incompatibility with CookieManager from extra_streamlit_components

### ISSUE THREAD

**Issue by informatica92** [m-wrzr/streamlit-searchbox#63]
Hi all, I found this very helpful custom component for Streamlit and I immediately started to test it in my already existing application.

Anyway, even adding a very basic sample, the entire component was not rendered at all in my tabs.
I spent many hours trying to remove components and see which one was affecting the visibility and finally I got it: 

This streamlit **searchbox** looks to be **not compatible** with **CookieManager** from **extra_streamlit_components** .

### Working example
```python
import streamlit as st
from streamlit_searchbox import st_searchbox
# import extra_streamlit_components as stx


def fake_search(searchterm: str) -> list[any]:
    v = ["Mario", "Gianni", "Giovanni", "Luigi", "Carlo", "Maria"]
    return [x for x in v if searchterm.lower() in x.lower()]


# cookie_manager = stx.CookieManager()
# st.session_state['username'] = cookie_manager.get("username")
st_searchbox(fake_search, key="searchbox0", label="Searchbox 0")

tab1, tab2, tab3 = st.tabs(["Tab 1", "Tab 2", "Tab 3"])
with tab1:

    st_searchbox(fake_search, key="searchbox1", label="Searchbox 1")
with tab2:
    st_searchbox(fake_search, key="searchbox2", label="Searchbox 2")
with tab3:
    st_searchbox(fake_search, key="searchbox3", label="Searchbox 3")
```
Result:
![image](https://github.com/user-attachments/assets/9617b007-f70e-4bf1-9e67-9537bb9fdf3d)

### NOT Working example
```python
import streamlit as st
from streamlit_searchbox import st_searchbox
import extra_streamlit_components as stx


def fake_search(searchterm: str) -> list[any]:
    v = ["Mario", "Gianni", "Giovanni", "Luigi", "Carlo", "Maria"]
    return [x for x in v if searchterm.lower() in x.lower()]


cookie_manager = stx.CookieManager()
st.session_state['username'] = cookie_manager.get("username")
st_searchbox(fake_search, key="searchbox0", label="Searchbox 0")

tab1, tab2, tab3 = st.tabs(["Tab 1", "Tab 2", "Tab 3"])
with tab1:

    st_searchbox(fake_search, key="searchbox1", label="Searchbox 1")
with tab2:
    st_searchbox(fake_search, key="searchbox2", label="Searchbox 2")
with tab3:
    st_searchbox(fake_search, key="searchbox3", label="Searchbox 3")
```
Result:
![image](https://github.com/user-attachments/assets/d5764d2d-7f8a-4eee-9417-523892ab6560)

Libraries: 
- **extra-streamlit-components**: 0.1.71
- **streamlit**: 1.38.0
- **streamlit-searchbox**: 0.1.17

Similar behavior also with streamlit: 1.37.1

Have you ever experienced/noticed such a behavior? Do you have an idea about how to fix?

**Comment by m-wrzr** [comment]
Hey 

I had a look at the code of the cookie manager in `extra_streamlit_components/CookieManager/__init__.py` and it looks like it's setting the height of all iframes to 0 via this css selector: https://github.com/Mohamed-512/Extra-Streamlit-Components/blob/master/extra_streamlit_components/CookieManager/__init__.py#L118

```
st.markdown(
       """ 
       <style>
       element-container:has(iframe[height="0"]) { display: none; }
       </style>
        """,
       unsafe_allow_html=True,
)
```

This makes it incompatible with other custom components that also use iframes, like this components or for example `AgGrid`. In the example below also nothing is visible.. I'll create a ticket in the cookie manager repo
```
from st_aggrid import AgGrid
import pandas as pd
import streamlit as st

import extra_streamlit_components as stx

cookie_manager = stx.CookieManager()
st.session_state["username"] = cookie_manager.get("username")

df = pd.read_csv(
    "https://raw.githubusercontent.com/fivethirtyeight/data/master/airline-safety/airline-safety.csv"
)
AgGrid(df)

```

**Comment by m-wrzr** [comment]
I'll close the issue, since it's not a problem with this component. Thanks for reporting and providing the concise example!

**Comment by informatica92** [comment]
Oh, great! Thanks for checking.
I'll keep an eye in this issue you mentioned.

Thanks once again!
